self.keyboard.tileWalk('a', 21.0)
self.keyboard.tileWalk('s', 28.0)
self.keyboard.keyDown('d')
self.keyboard.keyDown('w')
self.keyboard.tileWait(17.5)
self.keyboard.keyUp('w')
self.keyboard.tileWait(23.5)
self.keyboard.keyDown('s')
self.keyboard.tileWait(3.5)
self.keyboard.keyUp('s')
self.keyboard.tileWait(18.0)
self.keyboard.keyUp('d')
time.sleep(0.1)
self.keyboard.keyDown('s')
self.keyboard.tileWait(24.5)
self.keyboard.keyUp('s')
