self.keyboard.tileWalk('a', 21.0)
self.keyboard.tileWalk('s', 28.0)
self.keyboard.tileWalk('d', 9.0)
self.keyboard.multiTileWalk(['d', 'w'], 35.0)
self.keyboard.tileWalk('w', 6.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.2)
self.keyboard.keyUp('w')
time.sleep(0.5)
self.keyboard.tileWalk('d', 33.0)
self.keyboard.tileWalk('a', 6.0)
self.keyboard.tileWalk('s', 10.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.3)
self.keyboard.keyUp('s')
time.sleep(0.5)
self.keyboard.tileWalk('s', 1.5)
time.sleep(0.3)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.keyDown('e')
time.sleep(0.1)
self.keyboard.keyUp('e')
time.sleep(3.0)
self.keyboard.tileWalk('w', 5.0)
self.keyboard.tileWalk('d', 5.199999999999999)
self.keyboard.keyDown('e')
time.sleep(0.1)
self.keyboard.keyUp('e')
self.keyboard.keyDown('d')
self.keyboard.keyDown('s')
time.sleep(0.95)
self.keyboard.press('space')
self.keyboard.press('space')
time.sleep(1.7)
self.keyboard.keyUp('d')
self.keyboard.keyUp('s')
time.sleep(1.0)
self.keyboard.press('space')
time.sleep(2.0)
