self.keyboard.press('e')
time.sleep(0.55)
self.keyboard.press('space')
time.sleep(0.1)
self.keyboard.press('space')
time.sleep(2.35)
self.keyboard.press('space')
time.sleep(1.0)
self.keyboard.walk('s', 2.0)
self.keyboard.walk('d', 9.0)
self.keyboard.multiWalk(['d', 'w'], 35.0)
self.keyboard.walk('w', 6.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.2)
self.keyboard.keyUp('w')
time.sleep(0.5)
self.keyboard.walk('d', 33.0)
self.keyboard.walk('a', 6.0)
self.keyboard.walk('s', 10.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.3)
self.keyboard.keyUp('s')
time.sleep(0.5)
self.keyboard.walk('s', 1.5)
time.sleep(0.3)
