time.sleep(0.1)
time.sleep(0.79)
self.keyboard.press('space')
time.sleep(0.1)
self.keyboard.press('space')
time.sleep(3.05)
self.keyboard.press('space')
time.sleep(1.0)
self.keyboard.walk('a', 9.0)
self.keyboard.multiWalk(['a', 's'], 35.0)
self.keyboard.walk('s', 6.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.2)
self.keyboard.keyUp('s')
time.sleep(0.5)
self.keyboard.walk('a', 33.0)
self.keyboard.walk('d', 6.0)
self.keyboard.walk('w', 10.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.3)
self.keyboard.keyUp('w')
time.sleep(0.5)
self.keyboard.walk('w', 1.5)
time.sleep(0.3)
