self.keyboard.walk('w', 12.0)
time.sleep(0.1)
self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('d')
time.sleep(0.4)
self.keyboard.walk('d', 1.0)
self.keyboard.walk('w', 4.0)
time.sleep(0.1)
self.keyboard.walk('d', 10.0)
self.keyboard.multiWalk(['d', 'w'], 18.0)
self.keyboard.walk('w', 2.5)
self.keyboard.walk('a', 5.0)
