self.keyboard.tileWalk('d', 5.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.6)
self.keyboard.keyUp('s')
time.sleep(0.3)
self.keyboard.multiTileWalk(['s', 'a'], 4.0)
self.keyboard.tileWalk('a', 9.0)
self.keyboard.multiTileWalk(['s', 'a'], 7.5)
self.keyboard.tileWalk('s', 42.0)
self.keyboard.multiTileWalk(['s', 'd'], 15.0)
self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('d')
time.sleep(0.25)
self.keyboard.keyDown('s')
self.keyboard.tileWait(4.0)
self.keyboard.keyUp('s')
time.sleep(0.07)
self.keyboard.keyDown('a')
self.keyboard.tileWait(41.0)
self.keyboard.keyUp('a')
self.keyboard.tileWalk('w', 12.0)
