self.keyboard.tileWalk('d', 5.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.6)
self.keyboard.keyUp('s')
time.sleep(0.3)
self.keyboard.keyDown('d')
self.keyboard.keyDown('s')
self.keyboard.tileWait(28.5)
self.keyboard.keyUp('d')
self.keyboard.tileWait(35.0)
self.keyboard.keyUp('s')
self.keyboard.multiTileWalk(['d', 's'], 19.0)
self.keyboard.tileWalk('d', 11.0)
self.keyboard.tileWalk('a', 1.0)
self.keyboard.tileWalk('w', 4.5)
self.keyboard.tileWalk('d', 3.0)
self.keyboard.multiTileWalk(['d', 'w'], 2.0)
self.keyboard.tileWalk('d', 17.0)
self.keyboard.press('space')
time.sleep(0.3)
self.keyboard.keyDown('d')
time.sleep(0.2)
self.keyboard.keyUp('d')
time.sleep(0.5)
self.keyboard.tileWalk('d', 6.0)
time.sleep(0.05)
self.keyboard.tileWalk('s', 2.5)
self.keyboard.tileWalk('d', 5.0)
