self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.6)
self.keyboard.keyUp('w')
time.sleep(0.3)
self.keyboard.walk('w', 21.0)
self.keyboard.multiWalk(['a', 'w'], 8.0)
self.keyboard.walk('a', 5.0)
