self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('a')
time.sleep(0.25)
time.sleep(0.07)
self.keyboard.walk('w', 5.5)
self.keyboard.multiWalk(['w', 'd'], 25.0)
self.keyboard.walk('d', 5.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.6)
self.keyboard.keyUp('w')
time.sleep(0.3)
self.keyboard.multiWalk(['w', 'd'], 4.0)
self.keyboard.walk('d', 9.0)
self.keyboard.multiWalk(['w', 'd'], 7.5)
self.keyboard.walk('w', 42.0)
self.keyboard.multiWalk(['w', 'a'], 15.0)
self.keyboard.walk('a', 5.0)
