self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.6)
self.keyboard.keyUp('w')
time.sleep(0.3)
self.keyboard.multiWalk(['w', 'd'], 4.0)
self.keyboard.walk('d', 9.0)
self.keyboard.multiWalk(['w', 'd'], 7.5)
self.keyboard.walk('w', 32.5)
self.keyboard.multiWalk(['w', 'd'], 9.5)
self.keyboard.walk('a', 5.0)
