self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.6)
self.keyboard.keyUp('s')
time.sleep(0.3)
self.keyboard.multiWalk(['s', 'a'], 4.0)
self.keyboard.walk('a', 9.0)
self.keyboard.multiWalk(['s', 'a'], 7.5)
self.keyboard.walk('s', 32.5)
self.keyboard.multiWalk(['s', 'a'], 9.5)
self.keyboard.walk('d', 5.0)
