# Converted from Natro Macro paths/gtf-coconut.ahk
self.keyboard.keyDown('space', False)
self.keyboard.keyDown('d', False)
sleep(0.1)
self.keyboard.keyUp('space', False)
self.keyboard.tileWait(2)
self.keyboard.keyDown('w', False)
self.keyboard.tileWait(1.8)
self.keyboard.keyUp('w', False)
self.keyboard.tileWait(30)
self.keyboard.keyUp('d', False)
self.keyboard.keyDown('space', False)
sleep(0.3)
self.keyboard.keyUp('space', False)
self.keyboard.tileWalk('d', 4)
self.keyboard.tileWalk('w', 5)
self.keyboard.tileWalk('d', 3)
self.keyboard.keyDown('space', False)
sleep(0.3)
self.keyboard.keyUp('space', False)
self.keyboard.tileWalk('w', 6)
self.keyboard.keyDown('a', False)
self.keyboard.keyDown('w', False)
self.keyboard.tileWait(2)
self.keyboard.keyUp('w', False)
self.keyboard.keyUp('a', False)
self.keyboard.tileWalk('w', 8)
self.keyboard.keyDown('w', False)
self.keyboard.keyDown('d', False)
self.keyboard.tileWait(11)
self.keyboard.keyDown('space', False)
self.keyboard.keyUp('d', False)
sleep(0.2)
self.keyboard.keyUp('space', False)
sleep(1.1)
self.keyboard.keyDown('space', False)
sleep(0.2)
self.keyboard.keyUp('space', False)
self.keyboard.tileWait(18)
self.keyboard.keyUp('w', False)
self.keyboard.tileWalk('a', 13.5)
