# Converted from Natro Macro paths/gtf-strawberry.ahk
self.keyboard.keyDown('e', False)
sleep(0.1)
self.keyboard.keyUp('e', False)
self.keyboard.keyDown('d', False)
self.keyboard.keyDown('s', False)
sleep(0.7)
self.keyboard.press('space')
self.keyboard.press('space')
sleep(1.7)
self.keyboard.keyUp('d', False)
self.keyboard.keyUp('s', False)
self.keyboard.press('space')
self.keyboard.press('.')
self.keyboard.press('.')
sleep(2)
