self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('s')
time.sleep(0.4)
self.keyboard.walk('s', 4.0)
self.keyboard.walk('d', 6.0)
self.keyboard.walk('s', 9.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('s')
time.sleep(0.4)
self.keyboard.walk('s', 4.0)
self.keyboard.multiWalk(['s', 'a'], 10.0)
