self.keyboard.keyDown('s')
self.keyboard.keyDown('d')
self.keyboard.tileWait(11.5)
self.keyboard.keyUp('s')
self.keyboard.tileWait(40.0)
self.keyboard.keyDown('w')
self.keyboard.tileWait(18.0)
self.keyboard.keyUp('d')
self.keyboard.tileWait(7.0)
self.keyboard.keyUp('w')
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.tileWalk('w', 4.0)
self.keyboard.tileWalk('a', 6.0)
self.keyboard.tileWalk('w', 9.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.tileWalk('w', 4.0)
self.keyboard.multiTileWalk(['w', 'd'], 10.0)
