self.keyboard.walk('a', 5.0)
self.keyboard.multiWalk(['a', 'w'], 16.0)
self.keyboard.walk('d', 1.0)
self.keyboard.walk('s', 4.5)
self.keyboard.walk('a', 3.0)
self.keyboard.multiWalk(['a', 's'], 2.0)
self.keyboard.walk('a', 17.0)
self.keyboard.press('space')
time.sleep(0.3)
self.keyboard.keyDown('a')
time.sleep(0.2)
self.keyboard.keyUp('a')
time.sleep(0.5)
self.keyboard.walk('a', 6.0)
time.sleep(0.05)
self.keyboard.walk('w', 2.5)
