self.keyboard.keyDown('d')
self.keyboard.tileWait(17.5)
self.keyboard.keyDown('s')
self.keyboard.keyUp('d')
self.keyboard.tileWait(24.0)
self.keyboard.keyDown('d')
self.keyboard.tileWait(15.0)
self.keyboard.keyUp('s')
self.keyboard.tileWait(6.5)
self.keyboard.keyUp('d')
self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('d')
time.sleep(0.25)
self.keyboard.keyDown('s')
self.keyboard.tileWait(4.0)
self.keyboard.keyUp('s')
time.sleep(0.07)
self.keyboard.keyDown('a')
self.keyboard.tileWait(41.0)
self.keyboard.keyUp('a')
self.keyboard.multiTileWalk(['w', 'a'], 17.0)
self.keyboard.tileWalk('a', 7.0)
