self.keyboard.keyDown('d')
self.keyboard.tileWait(52.0)
self.keyboard.keyDown('s')
self.keyboard.tileWait(8.5)
self.keyboard.keyUp('d')
self.keyboard.tileWait(18.5)
self.keyboard.keyDown('d')
self.keyboard.tileWait(2.0)
self.keyboard.keyUp('d')
self.keyboard.tileWait(13.5)
self.keyboard.keyUp('s')
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.keyUp('s')
time.sleep(0.4)
self.keyboard.tileWalk('s', 2.0)
self.keyboard.multiTileWalk(['s', 'a'], 15.0)
self.keyboard.tileWalk('s', 5.0)
