self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.walk('w', 2.0)
self.keyboard.multiWalk(['w', 'd'], 15.0)
self.keyboard.walk('w', 5.0)
