self.keyboard.walk('a', 5.0)
time.sleep(0.1)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.walk('w', 10.0)
time.sleep(0.1)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.walk('w', 2.0)
self.keyboard.multiWalk(['w', 'a'], 14.0)
self.keyboard.walk('w', 2.5)
