self.keyboard.walk('d', 5.0)
time.sleep(0.1)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('s')
time.sleep(0.4)
self.keyboard.walk('s', 10.0)
time.sleep(0.1)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('s')
time.sleep(0.4)
self.keyboard.walk('s', 2.0)
self.keyboard.multiWalk(['s', 'd'], 14.0)
self.keyboard.walk('s', 2.5)
