time.sleep(0.1)
time.sleep(0.925)
self.keyboard.press('space')
self.keyboard.press('space')
time.sleep(4.5)
self.keyboard.keyUp('w')
time.sleep(0.5)
time.sleep(2.0)
self.keyboard.walk('s', 2.5)
self.keyboard.walk('w', 44.0)
self.keyboard.multiWalk(['a', 'w'], 26.0)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.walk('s', 7.0)
self.keyboard.walk('a', 6.0)
