self.keyboard.tileWalk('w', 2.5)
self.keyboard.tileWalk('s', 44.0)
self.keyboard.multiTileWalk(['d', 's'], 26.0)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.tileWalk('w', 7.0)
self.keyboard.tileWalk('d', 6.0)
self.keyboard.keyDown('e')
time.sleep(0.1)
self.keyboard.keyUp('e')
self.keyboard.keyDown('a')
time.sleep(1.85)
self.keyboard.press('space')
self.keyboard.press('space')
time.sleep(2.75)
self.keyboard.keyUp('a')
self.keyboard.keyDown('s')
time.sleep(1.15)
self.keyboard.keyUp('s')
self.keyboard.press('space')
time.sleep(2.0)
