self.keyboard.tileWalk('w', 2.5)
self.keyboard.tileWalk('s', 44.0)
self.keyboard.multiTileWalk(['d', 's'], 26.0)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.tileWalk('w', 7.0)
self.keyboard.tileWalk('d', 6.0)
self.keyboard.keyDown('e')
time.sleep(0.1)
self.keyboard.keyUp('e')
self.keyboard.keyDown('d')
self.keyboard.keyDown('s')
time.sleep(0.95)
self.keyboard.press('space')
self.keyboard.press('space')
time.sleep(2.7)
self.keyboard.keyUp('d')
time.sleep(0.5)
self.keyboard.keyUp('s')
time.sleep(0.6)
self.keyboard.press('space')
time.sleep(1.5)
