self.keyboard.multiWalk(['a', 'w'], 4.0)
self.keyboard.walk('w', 10.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('w')
self.keyboard.multiWalk(['d', 'w'], 19.0)
self.keyboard.walk('w', 3.5)
self.keyboard.walk('s', 2.5)
