self.keyboard.tileWalk('w', 2.5)
self.keyboard.keyDown('a')
self.keyboard.keyDown('s')
self.keyboard.tileWait(31.0)
self.keyboard.keyUp('a')
self.keyboard.tileWait(47.0)
self.keyboard.keyUp('s')
self.keyboard.multiTileWalk(['d', 's'], 4.0)
self.keyboard.tileWalk('s', 10.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('s')
self.keyboard.multiTileWalk(['a', 's'], 19.0)
self.keyboard.tileWalk('s', 3.5)
