self.keyboard.tileWalk('w', 2.5)
self.keyboard.keyDown('a')
self.keyboard.keyDown('s')
self.keyboard.tileWait(21.0)
self.keyboard.keyUp('a')
self.keyboard.keyUp('s')
self.keyboard.tileWalk('a', 40.0)
self.keyboard.multiTileWalk(['s', 'a'], 16.0)
self.keyboard.tileWalk('a', 1.0)
