self.keyboard.tileWalk('w', 2.5)
self.keyboard.keyDown('a')
self.keyboard.keyDown('s')
self.keyboard.tileWait(21.0)
self.keyboard.keyUp('a')
self.keyboard.keyUp('s')
self.keyboard.tileWalk('a', 45.0)
self.keyboard.tileWalk('s', 37.0)
self.keyboard.multiTileWalk(['s', 'a'], 10.0)
