self.keyboard.tileWalk('w', 2.5)
self.keyboard.keyDown('a')
self.keyboard.keyDown('s')
self.keyboard.tileWait(31.0)
self.keyboard.keyUp('a')
self.keyboard.tileWait(47.0)
self.keyboard.keyUp('s')
self.keyboard.tileWalk('d', 3.0)
