self.keyboard.tileWalk('s', 22.0)
self.keyboard.tileWalk('d', 33.0)
self.keyboard.keyDown('a')
self.keyboard.tileWait(0.3)
self.keyboard.keyDown('w')
self.keyboard.tileWait(26.5)
self.keyboard.keyUp('a')
self.keyboard.tileWait(21.7)
self.keyboard.keyDown('d')
self.keyboard.tileWait(2.7)
self.keyboard.keyUp('d')
self.keyboard.tileWait(15.0)
self.keyboard.keyDown('a')
self.keyboard.tileWait(27.9)
self.keyboard.keyUp('a')
self.keyboard.tileWait(23.3)
self.keyboard.keyUp('w')
