self.keyboard.tileWalk('s', 22.0)
self.keyboard.tileWalk('d', 33.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.6)
self.keyboard.keyUp('s')
self.keyboard.tileWalk('s', 10.0)
self.keyboard.tileWalk('w', 3.0)
self.keyboard.tileWalk('a', 22.0)
self.keyboard.multiTileWalk(['a', 's'], 20.0)
self.keyboard.tileWalk('a', 53.5)
self.keyboard.tileWalk('w', 38.0)
