self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.6)
self.keyboard.keyUp('w')
self.keyboard.walk('w', 10.0)
self.keyboard.walk('s', 3.0)
self.keyboard.walk('d', 22.0)
self.keyboard.multiWalk(['d', 'w'], 20.0)
self.keyboard.walk('d', 53.5)
self.keyboard.walk('s', 38.0)
