self.keyboard.multiWalk(['a', 'w'], 28.0)
self.keyboard.walk('w', 15.0)
self.keyboard.multiWalk(['d', 'w'], 4.0)
self.keyboard.walk('w', 48.0)
self.keyboard.press('space')
self.keyboard.walk('w', 4.0)
self.keyboard.walk('a', 4.0)
self.keyboard.walk('w', 9.0)
self.keyboard.press('space')
self.keyboard.walk('w', 4.0)
self.keyboard.multiWalk(['w', 'd'], 10.0)
self.keyboard.walk('w', 4.0)
