self.keyboard.multiWalk(['d', 's'], 28.0)
self.keyboard.walk('s', 15.0)
self.keyboard.multiWalk(['a', 's'], 4.0)
self.keyboard.walk('s', 48.0)
self.keyboard.press('space')
self.keyboard.walk('s', 4.0)
self.keyboard.walk('d', 4.0)
self.keyboard.walk('s', 9.0)
self.keyboard.press('space')
self.keyboard.walk('s', 4.0)
self.keyboard.multiWalk(['s', 'a'], 10.0)
self.keyboard.walk('s', 4.0)
