self.keyboard.tileWalk('s', 22.0)
self.keyboard.tileWalk('d', 33.0)
self.keyboard.keyDown('w')
self.keyboard.keyDown('a')
self.keyboard.tileWait(27.6)
self.keyboard.keyUp('a')
self.keyboard.tileWait(12.3)
self.keyboard.keyDown('d')
self.keyboard.tileWait(19.3)
self.keyboard.keyUp('d')
self.keyboard.tileWait(10.8)
self.keyboard.keyUp('w')
