self.keyboard.tileWalk('s', 22.0)
self.keyboard.tileWalk('d', 33.0)
self.keyboard.keyDown('a')
self.keyboard.keyDown('w')
self.keyboard.tileWait(27.4)
self.keyboard.keyUp('a')
self.keyboard.tileWait(21.0)
self.keyboard.keyUp('w')
self.keyboard.keyDown('a')
self.keyboard.tileWait(15.0)
self.keyboard.keyUp('a')
