self.keyboard.tileWalk('s', 22.0)
self.keyboard.tileWalk('d', 33.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.6)
self.keyboard.keyUp('s')
self.keyboard.tileWalk('s', 10.0)
self.keyboard.tileWalk('w', 3.0)
self.keyboard.tileWalk('a', 22.0)
self.keyboard.multiTileWalk(['a', 's'], 20.0)
self.keyboard.tileWalk('a', 20.0)
self.keyboard.tileWalk('w', 5.5)
time.sleep(0.05)
self.keyboard.tileWalk('s', 2.0)
time.sleep(0.05)
self.keyboard.tileWalk('a', 54.0)
