time.sleep(0.1)
time.sleep(1.85)
self.keyboard.press('space')
self.keyboard.press('space')
time.sleep(3.05)
self.keyboard.press(',')
self.keyboard.press(',')
time.sleep(0.85)
self.keyboard.press('space')
self.keyboard.press('.')
self.keyboard.press('.')
time.sleep(2.0)
self.keyboard.walk('a', 1.0)
self.keyboard.walk('w', 4.5)
self.keyboard.walk('d', 3.0)
self.keyboard.multiWalk(['d', 'w'], 2.0)
self.keyboard.walk('d', 17.0)
self.keyboard.press('space')
time.sleep(0.3)
self.keyboard.keyDown('d')
time.sleep(0.2)
self.keyboard.keyUp('d')
time.sleep(0.5)
self.keyboard.walk('d', 6.0)
time.sleep(0.05)
self.keyboard.walk('s', 2.5)
