self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.6)
self.keyboard.keyUp('s')
self.keyboard.walk('s', 10.0)
self.keyboard.walk('w', 3.0)
self.keyboard.walk('a', 22.0)
self.keyboard.multiWalk(['a', 's'], 20.0)
self.keyboard.walk('a', 55.0)
self.keyboard.multiWalk(['w', 'a'], 27.0)
self.keyboard.walk('w', 17.0)
