time.sleep(0.05)
time.sleep(0.12)
self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('d')
self.keyboard.walk('s', 5.0)
self.keyboard.multiWalk(['s', 'd'], 23.0)
self.keyboard.walk('d', 2.0)
