self.keyboard.tileWalk('s', 22.0)
self.keyboard.tileWalk('d', 33.0)
self.keyboard.keyDown('a')
self.keyboard.keyDown('w')
self.keyboard.tileWait(30.0)
self.keyboard.keyUp('a')
self.keyboard.tileWait(4.7)
self.keyboard.keyUp('w')
time.sleep(0.05)
self.keyboard.keyDown('a')
self.keyboard.tileWait(23.0)
self.keyboard.keyDown('s')
self.keyboard.tileWait(7.0)
self.keyboard.keyUp('a')
self.keyboard.keyUp('s')
self.keyboard.keyDown('w')
self.keyboard.tileWait(6.6)
self.keyboard.keyUp('w')
time.sleep(0.12)
self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('a')
self.keyboard.tileWalk('s', 3.0)
self.keyboard.multiTileWalk(['s', 'a'], 15.0)
self.keyboard.tileWalk('a', 8.0)
