self.keyboard.tileWalk('w', 28.0)
self.keyboard.tileWalk('a', 17.0)
self.keyboard.tileWalk('d', 13.5)
time.sleep(0.075)
self.keyboard.press('space')
time.sleep(0.3)
self.keyboard.tileWalk('w', 2.4)
time.sleep(0.3)
self.keyboard.tileWalk('a', 14.0)
self.keyboard.multiTileWalk(['w', 'a'], 28.0)
self.keyboard.tileWalk('w', 35.0)
self.keyboard.multiTileWalk(['a', 'w'], 14.0)
self.keyboard.tileWalk('w', 32.0)
