self.keyboard.walk('a', 23.0)
self.keyboard.walk('s', 16.0)
self.keyboard.multiWalk(['s', 'd'], 5.0)
self.keyboard.walk('s', 15.0)
self.keyboard.multiWalk(['a', 's'], 4.0)
self.keyboard.walk('s', 27.0)
self.keyboard.multiWalk(['s', 'd'], 27.0)
self.keyboard.walk('s', 19.5)
