self.keyboard.tileWalk('w', 28.0)
self.keyboard.tileWalk('a', 17.0)
self.keyboard.tileWalk('d', 23.0)
self.keyboard.tileWalk('w', 16.0)
self.keyboard.multiTileWalk(['w', 'a'], 5.0)
self.keyboard.tileWalk('w', 15.0)
self.keyboard.multiTileWalk(['d', 'w'], 4.0)
self.keyboard.tileWalk('w', 27.0)
self.keyboard.multiTileWalk(['w', 'a'], 27.0)
self.keyboard.tileWalk('w', 19.5)
