self.keyboard.tileWalk('w', 28.0)
self.keyboard.tileWalk('a', 17.0)
self.keyboard.tileWalk('s', 18.0)
time.sleep(0.05)
self.keyboard.tileWalk('a', 47.0)
self.keyboard.tileWalk('w', 38.0)
self.keyboard.tileWalk('a', 2.5)
