self.keyboard.tileWalk('w', 28.0)
self.keyboard.tileWalk('a', 17.0)
self.keyboard.tileWalk('d', 23.0)
self.keyboard.tileWalk('w', 15.0)
self.keyboard.multiTileWalk(['w', 'a'], 5.0)
self.keyboard.tileWalk('w', 15.0)
self.keyboard.multiTileWalk(['d', 'w'], 4.0)
self.keyboard.tileWalk('w', 48.0)
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.tileWalk('w', 4.0)
self.keyboard.tileWalk('a', 4.0)
self.keyboard.tileWalk('w', 9.0)
self.keyboard.press('space')
time.sleep(0.35)
self.keyboard.tileWalk('w', 4.0)
self.keyboard.multiTileWalk(['w', 'd'], 10.0)
self.keyboard.tileWalk('w', 4.0)
