self.keyboard.tileWalk('w', 28.0)
self.keyboard.tileWalk('a', 17.0)
self.keyboard.tileWalk('d', 23.0)
self.keyboard.tileWalk('w', 14.0)
self.keyboard.multiTileWalk(['w', 'a'], 5.0)
self.keyboard.tileWalk('w', 19.0)
self.keyboard.multiTileWalk(['w', 'd'], 20.5)
self.keyboard.tileWalk('w', 8.5)
