self.keyboard.walk('a', 23.0)
self.keyboard.walk('s', 14.0)
self.keyboard.multiWalk(['s', 'd'], 5.0)
self.keyboard.walk('s', 19.0)
self.keyboard.multiWalk(['s', 'a'], 20.5)
self.keyboard.walk('s', 8.5)
