self.keyboard.tileWalk('w', 28.0)
self.keyboard.tileWalk('a', 17.0)
self.keyboard.tileWalk('d', 23.0)
self.keyboard.tileWalk('w', 14.0)
self.keyboard.multiTileWalk(['w', 'a'], 6.0)
self.keyboard.tileWalk('w', 26.0)
self.keyboard.tileWalk('a', 13.0)
