self.keyboard.tileWalk('w', 28.0)
self.keyboard.tileWalk('a', 17.0)
self.keyboard.tileWalk('s', 18.0)
time.sleep(0.05)
self.keyboard.tileWalk('a', 20.0)
self.keyboard.tileWalk('w', 5.5)
time.sleep(0.05)
self.keyboard.tileWalk('s', 2.0)
time.sleep(0.05)
self.keyboard.tileWalk('a', 51.0)
