self.keyboard.tileWalk('w', 28.0)
self.keyboard.tileWalk('a', 17.0)
self.keyboard.tileWalk('s', 18.0)
time.sleep(0.05)
self.keyboard.tileWalk('d', 52.0)
self.keyboard.multiTileWalk(['w', 'd'], 27.0)
self.keyboard.tileWalk('w', 17.0)
