self.keyboard.walk('a', 13.5)
time.sleep(0.075)
self.keyboard.press('space')
self.keyboard.walk('s', 2.4)
self.keyboard.walk('d', 14.0)
self.keyboard.multiWalk(['s', 'd'], 27.0)
self.keyboard.walk('d', 7.0)
