time.sleep(0.05)
time.sleep(0.55)
self.keyboard.press('space')
self.keyboard.press('space')
self.keyboard.press('space')
time.sleep(1.0)
self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('d')
time.sleep(0.6)
self.keyboard.multiWalk(['w', 'd'], 4.7)
self.keyboard.walk('d', 2.0)
