self.keyboard.tileWalk('a', 27.0)
self.keyboard.tileWalk('s', 21.0)
self.keyboard.keyDown('w')
self.keyboard.keyDown('d')
self.keyboard.tileWait(34.3)
self.keyboard.keyUp('w')
self.keyboard.tileWait(5.3)
self.keyboard.keyUp('d')
time.sleep(0.075)
self.keyboard.keyDown('w')
self.keyboard.tileWait(13.3)
self.keyboard.keyDown('d')
self.keyboard.tileWait(12.1)
self.keyboard.keyUp('w')
self.keyboard.keyUp('d')
