time.sleep(0.05)
time.sleep(3.5)
self.keyboard.walk('w', 12.0)
self.keyboard.walk('a', 1.0)
self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('a')
time.sleep(0.6)
self.keyboard.multiWalk(['s', 'a'], 4.7)
self.keyboard.walk('a', 2.0)
