self.keyboard.walk('a', 5.0)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('e')
self.keyboard.press('space')
self.keyboard.press('space')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(0.7)
self.keyboard.walk('d', 11.0)
self.keyboard.walk('s', 7.0)
self.keyboard.walk('w', 10.5)
self.keyboard.press(',')
self.keyboard.press(',')
time.sleep(0.1)
self.keyboard.walk('s', 2.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('s')
time.sleep(0.4)
self.keyboard.walk('s', 2.0)
self.keyboard.multiWalk(['s', 'a'], 4.5)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('a')
time.sleep(0.6)
self.keyboard.multiWalk(['s', 'a'], 4.7)
self.keyboard.walk('a', 2.0)
