self.keyboard.press('.')
time.sleep(0.05)
self.keyboard.press('space')
time.sleep(0.2)
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.press('space')
time.sleep(1.3)
self.keyboard.walk('w', 3.5)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('a')
time.sleep(0.6)
self.keyboard.multiWalk(['s', 'a'], 4.7)
self.keyboard.walk('a', 2.0)
