time.sleep(0.1)
time.sleep(1.85)
self.keyboard.press('space')
self.keyboard.press('space')
time.sleep(2.75)
time.sleep(1.15)
time.sleep(2.0)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('e')
self.keyboard.press('space')
self.keyboard.press('space')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(0.7)
self.keyboard.walk('a', 11.0)
self.keyboard.walk('w', 7.0)
self.keyboard.walk('s', 10.5)
self.keyboard.press(',')
self.keyboard.press(',')
time.sleep(0.1)
self.keyboard.walk('w', 2.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.walk('w', 2.0)
self.keyboard.multiWalk(['w', 'd'], 4.5)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('d')
time.sleep(0.6)
self.keyboard.multiWalk(['w', 'd'], 4.7)
self.keyboard.walk('d', 2.0)
