self.keyboard.tileWalk('a', 27.0)
self.keyboard.tileWalk('s', 21.0)
self.keyboard.keyDown('d')
self.keyboard.keyDown('w')
self.keyboard.tileWait(22.75)
self.keyboard.keyUp('w')
self.keyboard.tileWait(37.75)
self.keyboard.keyDown('w')
self.keyboard.keyUp('d')
self.keyboard.tileWait(9.75)
self.keyboard.keyUp('w')
self.keyboard.keyDown('d')
self.keyboard.tileWait(15.0)
self.keyboard.keyUp('d')
self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('d')
time.sleep(0.6)
self.keyboard.multiTileWalk(['w', 'd'], 4.7)
self.keyboard.tileWalk('d', 2.0)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('e')
time.sleep(0.22)
self.keyboard.press('space')
time.sleep(0.07)
self.keyboard.press('space')
time.sleep(2.65)
self.keyboard.press('.')
time.sleep(1.0)
self.keyboard.press('.')
time.sleep(0.2)
self.keyboard.press('space')
time.sleep(0.7)
self.keyboard.tileWalk('a', 11.0)
self.keyboard.tileWalk('w', 7.0)
self.keyboard.tileWalk('s', 10.5)
self.keyboard.press(',')
self.keyboard.press(',')
time.sleep(0.1)
self.keyboard.tileWalk('w', 2.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.tileWalk('w', 2.0)
self.keyboard.multiTileWalk(['w', 'd'], 4.5)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.keyDown('e')
time.sleep(0.1)
self.keyboard.keyUp('e')
self.keyboard.keyDown('a')
time.sleep(1.85)
self.keyboard.press('space')
self.keyboard.press('space')
time.sleep(2.75)
self.keyboard.keyUp('a')
self.keyboard.keyDown('s')
time.sleep(1.15)
self.keyboard.keyUp('s')
self.keyboard.press('space')
time.sleep(2.0)
