self.keyboard.tileWalk('a', 27.0)
self.keyboard.tileWalk('s', 21.0)
self.keyboard.keyDown('w')
self.keyboard.keyDown('d')
self.keyboard.tileWait(12.5)
self.keyboard.keyUp('w')
self.keyboard.tileWait(36.8)
self.keyboard.keyUp('d')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(3.4)
self.keyboard.press(',')
self.keyboard.press(',')
