self.keyboard.tileWalk('a', 27.0)
self.keyboard.tileWalk('s', 21.0)
self.keyboard.keyDown('d')
self.keyboard.keyDown('w')
self.keyboard.tileWait(22.75)
self.keyboard.keyUp('w')
self.keyboard.tileWait(37.75)
self.keyboard.keyDown('w')
self.keyboard.keyUp('d')
self.keyboard.tileWait(9.75)
self.keyboard.keyUp('w')
self.keyboard.keyDown('d')
self.keyboard.tileWait(15.0)
self.keyboard.keyUp('d')
self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('d')
time.sleep(0.6)
self.keyboard.multiTileWalk(['w', 'd'], 4.7)
self.keyboard.tileWalk('d', 2.0)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.keyDown('e')
time.sleep(0.05)
self.keyboard.keyUp('e')
time.sleep(0.6)
self.keyboard.press('space')
time.sleep(0.1)
self.keyboard.press('space')
time.sleep(1.48)
self.keyboard.press('space')
time.sleep(1.3)
self.keyboard.press('.')
self.keyboard.press('.')
