self.keyboard.tileWalk('a', 27.0)
self.keyboard.tileWalk('s', 21.0)
self.keyboard.keyDown('d')
self.keyboard.keyDown('w')
self.keyboard.tileWait(34.75)
self.keyboard.keyUp('w')
self.keyboard.tileWait(15.5)
self.keyboard.keyUp('d')
self.keyboard.keyDown('w')
self.keyboard.tileWait(10.5)
self.keyboard.keyUp('w')
time.sleep(0.11)
self.keyboard.keyDown('d')
self.keyboard.tileWait(15.0)
self.keyboard.keyUp('d')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(0.43)
self.keyboard.press('.')
time.sleep(2.5)
self.keyboard.press('space')
time.sleep(0.5)
