self.keyboard.keyDown('w')
self.keyboard.tileWait(25.0)
self.keyboard.keyDown('d')
self.keyboard.tileWait(9.5)
self.keyboard.keyUp('d')
self.keyboard.tileWait(22.5)
self.keyboard.keyUp('w')
self.keyboard.keyDown('a')
self.keyboard.tileWait(7.0)
self.keyboard.keyUp('a')
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.tileWalk('w', 4.0)
self.keyboard.tileWalk('d', 1.0)
self.keyboard.tileWalk('w', 9.0)
time.sleep(0.25)
self.keyboard.multiTileWalk(['w', 'd'], 11.0)
self.keyboard.tileWalk('w', 22.0)
