self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.walk('w', 4.0)
self.keyboard.walk('d', 1.0)
self.keyboard.walk('w', 9.0)
time.sleep(0.25)
self.keyboard.multiWalk(['w', 'd'], 11.0)
self.keyboard.walk('w', 22.0)
