self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('s')
time.sleep(0.4)
self.keyboard.walk('s', 4.0)
self.keyboard.walk('a', 1.0)
self.keyboard.walk('s', 9.0)
time.sleep(0.25)
self.keyboard.multiWalk(['s', 'a'], 11.0)
self.keyboard.walk('s', 22.0)
