self.keyboard.walk('w', 25.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.walk('w', 4.0)
self.keyboard.walk('a', 8.0)
self.keyboard.walk('w', 9.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.walk('w', 4.0)
self.keyboard.multiWalk(['w', 'd'], 10.0)
