self.keyboard.keyDown('w')
self.keyboard.tileWait(25.5)
self.keyboard.keyDown('d')
self.keyboard.tileWait(10.5)
self.keyboard.keyUp('w')
self.keyboard.tileWait(12.0)
self.keyboard.keyDown('w')
self.keyboard.tileWait(22.0)
self.keyboard.keyUp('w')
self.keyboard.keyUp('d')
self.keyboard.tileWalk('w', 25.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.tileWalk('w', 4.0)
self.keyboard.tileWalk('a', 8.0)
self.keyboard.tileWalk('w', 9.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.tileWalk('w', 4.0)
self.keyboard.multiTileWalk(['w', 'd'], 10.0)
