self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.keyUp('d')
time.sleep(0.3)
self.keyboard.tileWalk('s', 5.0)
self.keyboard.tileWalk('d', 13.0)
time.sleep(0.7)
self.keyboard.tileWalk('s', 8.0)
self.keyboard.tileWalk('a', 1.0)
self.keyboard.tileWalk('w', 4.5)
self.keyboard.tileWalk('d', 3.0)
self.keyboard.multiTileWalk(['d', 'w'], 2.0)
self.keyboard.tileWalk('d', 17.0)
self.keyboard.press('space')
time.sleep(0.3)
self.keyboard.keyDown('d')
time.sleep(0.2)
self.keyboard.keyUp('d')
time.sleep(0.5)
self.keyboard.tileWalk('d', 6.0)
time.sleep(0.05)
self.keyboard.tileWalk('s', 2.5)
self.keyboard.tileWalk('d', 5.0)
