self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('a')
time.sleep(0.25)
time.sleep(0.07)
self.keyboard.walk('w', 5.5)
self.keyboard.multiWalk(['w', 'd'], 25.0)
self.keyboard.walk('d', 5.0)
