self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('a')
time.sleep(0.25)
time.sleep(0.07)
self.keyboard.multiWalk(['s', 'd'], 17.0)
self.keyboard.walk('d', 7.0)
