self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.keyUp('d')
time.sleep(0.3)
self.keyboard.tileWalk('s', 5.0)
self.keyboard.tileWalk('d', 13.0)
time.sleep(0.7)
self.keyboard.tileWalk('s', 8.0)
self.keyboard.tileWalk('d', 16.0)
time.sleep(0.1)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.keyUp('s')
time.sleep(0.4)
self.keyboard.tileWalk('s', 2.0)
self.keyboard.multiTileWalk(['s', 'a'], 15.0)
self.keyboard.tileWalk('s', 5.0)
