self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.keyUp('a')
time.sleep(0.3)
self.keyboard.walk('w', 5.0)
self.keyboard.walk('a', 13.0)
time.sleep(0.7)
self.keyboard.walk('w', 8.0)
self.keyboard.walk('a', 16.0)
time.sleep(0.1)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.walk('w', 2.0)
self.keyboard.multiWalk(['w', 'd'], 15.0)
self.keyboard.walk('w', 5.0)
