self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.keyUp('d')
time.sleep(0.25)
self.keyboard.tileWalk('d', 1.0)
self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.keyUp('d')
time.sleep(0.25)
self.keyboard.tileWalk('d', 6.0)
time.sleep(0.6)
self.keyboard.tileWalk('d', 15.5)
self.keyboard.multiTileWalk(['d', 'w'], 4.0)
