self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.keyUp('a')
time.sleep(0.25)
self.keyboard.walk('a', 1.0)
self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.keyUp('a')
time.sleep(0.25)
self.keyboard.walk('a', 6.0)
time.sleep(0.6)
self.keyboard.walk('a', 15.5)
self.keyboard.multiWalk(['a', 's'], 4.0)
