self.keyboard.walk("s", 0.1)
self.keyboard.press("space")
self.keyboard.walk("a", 13, False)

# Converted from Natro Macro paths/gtc-antpass.ahk
self.keyboard.tileWalk('w', 3)
self.keyboard.keyDown('w', False)
self.keyboard.keyDown('space', False)
sleep(0.3)
self.keyboard.keyUp('space', False)
self.keyboard.tileWalk('d', 5)
self.keyboard.keyDown('space', False)
sleep(0.3)
self.keyboard.keyUp('space', False)
self.keyboard.keyUp('w', False)
sleep(0.5)
self.keyboard.tileWalk('w', 2)
self.keyboard.tileWalk('d', 15)
self.keyboard.keyDown('w', False)
self.keyboard.keyDown('d', False)
self.keyboard.tileWait(6)
self.keyboard.keyUp('d', False)
self.keyboard.keyUp('w', False)
self.keyboard.tileWalk('w', 7)
self.keyboard.keyDown('s', False)
self.keyboard.keyDown('a', False)
self.keyboard.tileWait(5)
self.keyboard.keyUp('a', False)
self.keyboard.keyUp('s', False)
self.keyboard.tileWalk('w', 23)
self.keyboard.tileWalk('a', 12)
self.keyboard.keyDown('a', False)
self.keyboard.keyDown('w', False)
self.keyboard.tileWait(8)
self.keyboard.keyUp('w', False)
self.keyboard.keyUp('a', False)
self.keyboard.tileWalk('w', 10)
self.keyboard.tileWalk('d', 5)
self.keyboard.keyDown('w', False)
self.keyboard.keyDown('d', False)
self.keyboard.tileWait(25)
self.keyboard.keyUp('d', False)
self.keyboard.keyUp('w', False)
self.keyboard.tileWalk('a', 25)
self.keyboard.tileWalk('s', 17)
