self.keyboard.slowPress("e")
self.keyboard.press("shift")
self.keyboard.press(".")
self.keyboard.press(".")
sleep(0.8)
self.keyboard.slowPress("space")
self.keyboard.slowPress("space")
sleep(2)
self.keyboard.press(".")
sleep(0.5)
self.keyboard.press(",")
sleep(5)
self.keyboard.walk("a",1)
self.keyboard.press("shift")
self.keyboard.walk("s",4, applyHaste=True)
self.keyboard.walk("a",0.7)
self.keyboard.walk("w",2.5, applyHaste=True)
self.keyboard.slowPress("s")
self.keyboard.walk("a",3.5, applyHaste=True)