# Converted from Natro Macro paths/gtb-blue.ahk
global fields
fields = ["pine tree", "blue flower", "bamboo", "stump"]
self.keyboard.keyDown('e', False)
sleep(0.1)
self.keyboard.keyUp('e', False)
self.keyboard.keyDown('a', False)
sleep(0.7)
self.keyboard.press('space')
self.keyboard.press('space')
sleep(4.45)
self.keyboard.keyUp('a', False)
self.keyboard.press('space')
sleep(1)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.keyDown('s', False)
self.keyboard.keyDown('a', False)
self.keyboard.tileWait(4)
self.keyboard.keyUp('a', False)
self.keyboard.keyUp('s', False)
self.keyboard.keyDown('w', False)
self.keyboard.keyDown('a', False)
self.keyboard.tileWait(8)
self.keyboard.keyUp('a', False)
self.keyboard.keyUp('w', False)
self.keyboard.tileWalk('w', 6)
self.keyboard.tileWalk('s', 5)
self.keyboard.tileWalk('d', 8)
self.keyboard.tileWalk('w', 30)
self.keyboard.keyDown('space', False)
sleep(0.1)
self.keyboard.keyUp('space', False)
self.keyboard.tileWalk('w', 6)
self.keyboard.tileWalk('d', 5)
self.keyboard.keyDown('d', False)
self.keyboard.keyDown('s', False)
self.keyboard.tileWait(9)
self.keyboard.keyUp('s', False)
self.keyboard.keyUp('d', False)
self.keyboard.tileWalk('d', 4)
self.keyboard.tileWalk('a', 2)
self.keyboard.tileWalk('s', 21)
self.keyboard.keyDown('w', False)
self.keyboard.keyDown('a', False)
self.keyboard.tileWait(3.4)
self.keyboard.keyUp('a', False)
self.keyboard.keyUp('w', False)
self.keyboard.tileWalk('a', 16)
