self.keyboard.slowPress(",")
self.keyboard.slowPress("e")
self.keyboard.keyDown("w")
time.sleep(0.12)
self.keyboard.slowPress("space")
self.keyboard.slowPress("space")
time.sleep(3.5)
self.keyboard.keyUp("w")
self.keyboard.slowPress("space")
time.sleep(0.5)

self.keyboard.tileWalk("w", 1)
self.keyboard.tileWalk("d", 2)
self.keyboard.tileWalk("s", 11)
sleep(0.6)