# Converted from Natro Macro paths/gtc-lidart.ahk
self.keyboard.keyDown('e', False)
sleep(0.1)
self.keyboard.keyUp('e', False)
self.keyboard.keyDown('a', False)
self.keyboard.keyDown('s', False)
sleep(1.4)
self.keyboard.press('space')
self.keyboard.press('space')
sleep(1.1)
self.keyboard.keyUp('a', False)
sleep(0.65)
self.keyboard.keyUp('s', False)
self.keyboard.press('space')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('.')
sleep(1.5)
self.keyboard.keyDown('d', False)
self.keyboard.keyDown('w', False)
self.keyboard.tileWait(4)
self.keyboard.keyUp('w', False)
self.keyboard.keyUp('d', False)
self.keyboard.tileWalk('w', 23)
self.keyboard.tileWalk('a', 9)
self.keyboard.tileWalk('w', 3)
self.keyboard.tileWalk('a', 8)
self.keyboard.tileWalk('d', 3.6)
self.keyboard.tileWalk('w', 41)
self.keyboard.keyDown('space', False)
sleep(0.1)
self.keyboard.keyUp('space', False)
self.keyboard.tileWalk('w', 21)
self.keyboard.keyDown('space', False)
sleep(0.1)
self.keyboard.keyUp('space', False)
self.keyboard.tileWalk('w', 3)
sleep(1)
