# Converted from Natro Macro paths/gtc-normalmm.ahk
self.keyboard.keyDown('e', False)
sleep(0.1)
self.keyboard.keyUp('e', False)
sleep(2.5)
self.keyboard.tileWalk('w', 30)
self.keyboard.tileWalk('s', 2)
self.keyboard.tileWalk('a', 22)
self.keyboard.tileWalk('d', 12)
self.keyboard.tileWalk('a', 3)
self.keyboard.tileWalk('w', 5)
self.keyboard.press('.')
self.keyboard.press('.')
sleep(1)
