# Converted from Natro Macro paths/gtc-samovar.ahk
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.keyDown('e', False)
sleep(0.1)
self.keyboard.keyUp('e', False)
self.keyboard.keyDown('w', False)
sleep(2)
self.keyboard.press('space')
self.keyboard.press('space')
sleep(2.8)
self.keyboard.keyDown('a', False)
sleep(0.9)
self.keyboard.keyUp('a', False)
sleep(1)
self.keyboard.keyUp('w', False)
sleep(0.65)
self.keyboard.press('space')
sleep(1)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.tileWalk('w', 36)
self.keyboard.keyDown('space', False)
sleep(0.1)
self.keyboard.keyUp('space', False)
self.keyboard.tileWalk('w', 3)
self.keyboard.keyDown('w', False)
self.keyboard.keyDown('d', False)
self.keyboard.tileWait(10)
self.keyboard.keyUp('d', False)
self.keyboard.keyUp('w', False)
self.keyboard.keyDown('w', False)
self.keyboard.keyDown('a', False)
self.keyboard.tileWait(8)
self.keyboard.keyUp('a', False)
self.keyboard.keyUp('w', False)
self.keyboard.keyDown('space', False)
sleep(0.1)
self.keyboard.keyUp('space', False)
self.keyboard.keyDown('w', False)
self.keyboard.keyDown('a', False)
self.keyboard.tileWait(3.5)
self.keyboard.keyUp('a', False)
self.keyboard.keyUp('w', False)
self.keyboard.press('.')
self.keyboard.tileWalk('w', 3)
self.keyboard.keyDown('space', False)
sleep(0.1)
self.keyboard.keyUp('space', False)
self.keyboard.tileWalk('w', 6)
