#Ahk code converted by Fuzzy Macro


self.keyboard.keyDown(tclrkey, False)
self.keyboard.tileWait(4 * size)
self.keyboard.keyUp(tclrkey, False)
self.keyboard.keyDown(tcfbkey, False)
self.keyboard.tileWait(2 * size)
self.keyboard.keyUp(tcfbkey, False)
self.keyboard.keyDown(afclrkey, False)
self.keyboard.tileWait(8 * size)
self.keyboard.keyUp(afclrkey, False)
self.keyboard.keyDown(tcfbkey, False)
self.keyboard.tileWait(2 * size)
self.keyboard.keyUp(tcfbkey, False)
self.keyboard.keyDown(tclrkey, False)
self.keyboard.tileWait(8 * size)
self.keyboard.keyUp(tclrkey, False)
self.keyboard.keyDown(afclrkey, False)
self.keyboard.keyDown(afcfbkey, False)
self.keyboard.tileWait( math.sqrt( ( ( 8 * size ) ** 2 ) + ( ( 8 * size ) ** 2 ) ) )
self.keyboard.keyUp(afclrkey, False)
self.keyboard.keyUp(afcfbkey, False)
self.keyboard.keyDown(tclrkey, False)
self.keyboard.tileWait(8 * size)
self.keyboard.keyUp(tclrkey, False)
self.keyboard.keyDown(tcfbkey, False)
self.keyboard.tileWait(2 * size)
self.keyboard.keyUp(tcfbkey, False)
self.keyboard.keyDown(afclrkey, False)
self.keyboard.tileWait(8 * size)
self.keyboard.keyUp(afclrkey, False)
self.keyboard.keyDown(tcfbkey, False)
self.keyboard.tileWait(7.5 * size + 10) # was 6.7 in cornerxsnake
self.keyboard.keyUp(tcfbkey, False)
self.keyboard.keyDown(afclrkey, False)
self.keyboard.tileWait(10 + width) # was 6 in cornerxsnake
self.keyboard.keyDown(tcfbkey, False)
self.keyboard.tileWait(3)
self.keyboard.keyUp(afclrkey, False)
self.keyboard.keyUp(tcfbkey, False)
self.keyboard.keyDown(tclrkey, False)
self.keyboard.tileWait(6 + width) # was 2 in cornerxsnake
self.keyboard.keyUp(tclrkey, False)
self.keyboard.keyDown(afcfbkey, False)
self.keyboard.tileWait(5)
self.keyboard.keyUp(afcfbkey, False)
self.keyboard.keyDown(tclrkey, False)
self.keyboard.tileWait(8 * size)
self.keyboard.keyUp(tclrkey, False)
self.keyboard.keyDown(afcfbkey, False)
self.keyboard.tileWait(2 * size)
self.keyboard.keyUp(afcfbkey, False)
self.keyboard.keyDown(afclrkey, False)
self.keyboard.tileWait(8 * size)
self.keyboard.keyUp(afclrkey, False)
self.keyboard.keyDown(afcfbkey, False)
self.keyboard.tileWait(2 * size)
self.keyboard.keyUp(afcfbkey, False)
self.keyboard.keyDown(tclrkey, False)
self.keyboard.tileWait(8 * size)
self.keyboard.keyUp(tclrkey, False)
self.keyboard.keyDown(afcfbkey, False)
self.keyboard.tileWait(2 * size)
self.keyboard.keyUp(afcfbkey, False)
self.keyboard.keyDown(afclrkey, False)
self.keyboard.tileWait(8 * size)
self.keyboard.keyUp(afclrkey, False)
self.keyboard.keyDown(afcfbkey, False)
self.keyboard.tileWait(3 * size)
self.keyboard.keyUp(afcfbkey, False)
self.keyboard.keyDown(tclrkey, False)
self.keyboard.tileWait(8 * size)
self.keyboard.keyUp(tclrkey, False)
self.keyboard.keyDown(tcfbkey, False)
self.keyboard.keyDown(afclrkey, False)
self.keyboard.tileWait( math.sqrt( ( ( 4 * size ) ** 2 ) + ( ( 4 * size ) ** 2 ) ) )
self.keyboard.keyUp(tcfbkey, False)
self.keyboard.keyUp(afclrkey, False)
# 231010 misc, based on cornerxsnake
# orangecheekbird here, major credit to misc all i did was update it with permission for natro 1.x :yippee:
# ty for all your work natro dev team!