# Ahk code converted by Fuzzy Macro

self.keyboard.keyDown(tcfbkey, False)
self.keyboard.tileWait(30)
self.keyboard.keyUp(tcfbkey, False)
self.keyboard.keyDown(afcfbkey, False)
self.keyboard.tileWait(2)
self.keyboard.keyUp(afcfbkey, False)
self.keyboard.keyDown(afclrkey, False)
self.keyboard.tileWait(1.75)
self.keyboard.keyUp(afclrkey, False)
self.keyboard.keyDown(afcfbkey, False)
self.keyboard.tileWait(26)
self.keyboard.keyUp(afcfbkey, False)
self.keyboard.keyDown(tclrkey, False)
self.keyboard.tileWait(24)
self.keyboard.keyUp(tclrkey, False)
self.keyboard.keyDown(tcfbkey, False)
self.keyboard.tileWait(2)
self.keyboard.keyUp(tcfbkey, False)
self.keyboard.keyDown(afclrkey, False)
self.keyboard.tileWait(18)
self.keyboard.keyUp(afclrkey, False)
