self.keyboard.tileWalk('w', 2.5)
self.keyboard.multiTileWalk(['w', 'a'], 10.0)
self.keyboard.tileWalk('w', 3.0)
self.keyboard.keyDown('d')
self.keyboard.tileWait(22.0)
self.keyboard.keyUp('d')
time.sleep(0.1)
self.keyboard.keyDown('w')
self.keyboard.tileWait(5.5)
self.keyboard.keyUp('w')
time.sleep(0.6)
self.keyboard.keyDown('s')
self.keyboard.tileWait(7.0)
self.keyboard.keyUp('s')
time.sleep(0.1)
self.keyboard.keyDown('a')
self.keyboard.tileWait(8.0)
self.keyboard.keyUp('a')
self.keyboard.keyDown('d')
self.keyboard.tileWait(5.0)
self.keyboard.keyUp('d')
time.sleep(0.05)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(1.5)
self.keyboard.press('space')
time.sleep(1.5)
self.keyboard.press(',')
self.keyboard.press(',')
