self.keyboard.press('space')
self.keyboard.press('space')
self.keyboard.walk('s', 4.0)
time.sleep(0.1)
time.sleep(0.6)
time.sleep(0.1)
time.sleep(0.05)
self.keyboard.walk(' FwdKey ', 2.5)
self.keyboard.multiWalk([' FwdKey ', ' LeftKey '], 10.0)
self.keyboard.walk(' FwdKey ', 3.0)
