self.keyboard.press('space')
time.sleep(1.28)
time.sleep(1.0)
time.sleep(0.66)
self.keyboard.press('space')
time.sleep(0.8)
self.keyboard.walk('w', 26.0)
self.keyboard.keyDown('w')
self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.2)
self.keyboard.keyUp('w')
self.keyboard.keyUp('a')
time.sleep(0.7)
self.keyboard.walk('d', 3.0)
self.keyboard.walk('w', 5.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.2)
self.keyboard.keyUp('w')
time.sleep(0.7)
self.keyboard.walk('a', 8.0)
self.keyboard.walk('s', 12.0)
self.keyboard.walk(' FwdKey ', 2.5)
self.keyboard.multiWalk([' FwdKey ', ' LeftKey '], 10.0)
self.keyboard.walk(' FwdKey ', 3.0)
