self.keyboard.tileWalk('w', 2.5)
self.keyboard.multiTileWalk(['w', 'a'], 10.0)
self.keyboard.tileWalk('w', 3.0)
self.keyboard.tileWalk('s', 26.0)
self.keyboard.keyDown('s')
self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.2)
self.keyboard.keyUp('s')
self.keyboard.keyUp('d')
time.sleep(0.7)
self.keyboard.tileWalk('a', 3.0)
self.keyboard.tileWalk('s', 5.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.2)
self.keyboard.keyUp('s')
time.sleep(0.7)
self.keyboard.tileWalk('d', 8.0)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.tileWalk('w', 12.0)
self.keyboard.press('space')
time.sleep(1.28)
self.keyboard.press(',')
time.sleep(1.0)
self.keyboard.press(',')
time.sleep(0.66)
self.keyboard.press('space')
time.sleep(0.8)
self.keyboard.press(',')
self.keyboard.press(',')
