self.keyboard.tileWalk('w', 2.5)
self.keyboard.multiTileWalk(['w', 'a'], 10.0)
self.keyboard.tileWalk('w', 3.0)
self.keyboard.keyDown('d')
self.keyboard.keyDown('s')
self.keyboard.tileWait(24.5)
self.keyboard.keyUp('s')
self.keyboard.tileWait(20.5)
self.keyboard.keyUp('d')
self.keyboard.keyDown('s')
self.keyboard.tileWait(11.5)
self.keyboard.keyUp('s')
self.keyboard.keyDown('d')
self.keyboard.tileWait(3.5)
self.keyboard.keyUp('d')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(3.2)
self.keyboard.press('.')
self.keyboard.press('.')
time.sleep(1.3)
self.keyboard.press('space')
time.sleep(1.5)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.tileWalk('a', 5.0)
