self.keyboard.press('space')
time.sleep(3.0)
time.sleep(0.4)
time.sleep(0.5)
self.keyboard.press('space')
time.sleep(0.97)
self.keyboard.walk('s', 26.0)
self.keyboard.keyDown('s')
self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.2)
self.keyboard.keyUp('s')
self.keyboard.keyUp('d')
time.sleep(0.7)
self.keyboard.walk('a', 3.0)
self.keyboard.walk('s', 5.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.2)
self.keyboard.keyUp('s')
time.sleep(0.7)
self.keyboard.walk('d', 8.0)
self.keyboard.walk('w', 12.0)
self.keyboard.walk(' FwdKey ', 2.5)
self.keyboard.multiWalk([' FwdKey ', ' LeftKey '], 10.0)
self.keyboard.walk(' FwdKey ', 3.0)
