self.keyboard.tileWalk('w', 2.5)
self.keyboard.multiTileWalk(['w', 'a'], 10.0)
self.keyboard.tileWalk('w', 3.0)
self.keyboard.keyDown('d')
self.keyboard.tileWait(11.5)
self.keyboard.keyDown('w')
self.keyboard.tileWait(5.5)
self.keyboard.keyUp('d')
self.keyboard.tileWait(25.0)
self.keyboard.keyUp('w')
time.sleep(1.74)
self.keyboard.keyDown('w')
self.keyboard.keyDown('a')
self.keyboard.tileWait(8.0)
self.keyboard.keyUp('w')
self.keyboard.tileWait(1.0)
self.keyboard.keyUp('a')
