self.keyboard.press('space')
time.sleep(1.4)
time.sleep(2.52)
time.sleep(2.9)
self.keyboard.press('space')
self.keyboard.walk(' FwdKey ', 2.5)
self.keyboard.multiWalk([' FwdKey ', ' LeftKey '], 10.0)
self.keyboard.walk(' FwdKey ', 3.0)
