self.keyboard.press('space')
time.sleep(1.9)
time.sleep(2.63)
time.sleep(1.14)
self.keyboard.press('space')
time.sleep(1.5)
self.keyboard.walk(' FwdKey ', 2.5)
self.keyboard.multiWalk([' FwdKey ', ' LeftKey '], 10.0)
self.keyboard.walk(' FwdKey ', 3.0)
