self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.walk('s', 32.0)
self.keyboard.multiWalk(['a', 'w'], 10.0)
time.sleep(0.075)
self.keyboard.walk('a', 29.0)
