self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.press(',')
time.sleep(1.0)
self.keyboard.press(',')
time.sleep(1.9)
self.keyboard.multiWalk(['Rightkey', 'w'], 12.0)
time.sleep(0.1)
self.keyboard.walk('w', 8.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.walk('w', 4.0)
self.keyboard.walk('a', 4.0)
self.keyboard.walk('w', 9.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.walk('w', 4.0)
self.keyboard.multiWalk(['w', 'd'], 10.0)
self.keyboard.multiWalk(['d', 's'], 10.0)
time.sleep(0.075)
self.keyboard.walk('d', 29.0)
