self.keyboard.tileWalk('w', 35.0)
self.keyboard.tileWalk('a', 19.0)
self.keyboard.multiTileWalk(['d', 's'], 10.0)
time.sleep(0.075)
self.keyboard.tileWalk('d', 29.0)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.press(',')
time.sleep(1.0)
self.keyboard.press(',')
time.sleep(1.9)
self.keyboard.keyDown('w')
self.keyboard.tileWait(3.5)
self.keyboard.keyUp('w')
self.keyboard.keyDown('d')
self.keyboard.tileWait(35.0)
self.keyboard.keyUp('d')
self.keyboard.multiTileWalk(['d', 'w'], 12.0)
time.sleep(0.1)
self.keyboard.tileWalk('w', 8.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.tileWalk('w', 4.0)
self.keyboard.tileWalk('a', 4.0)
self.keyboard.tileWalk('w', 9.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.tileWalk('w', 4.0)
self.keyboard.multiTileWalk(['w', 'd'], 10.0)
