time.sleep(0.1)
self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('a')
time.sleep(0.08)
self.keyboard.walk('w', 3.0)
self.keyboard.press('space')
time.sleep(2.05)
self.keyboard.press(',')
self.keyboard.press(',')
time.sleep(0.85)
self.keyboard.press('space')
self.keyboard.press('.')
self.keyboard.press('.')
time.sleep(1.6)
