self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.press('space')
time.sleep(3.0)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.walk('a', 1.5)
