self.keyboard.tileWalk('w', 35.0)
self.keyboard.tileWalk('a', 19.0)
self.keyboard.multiTileWalk(['d', 's'], 10.0)
time.sleep(0.075)
self.keyboard.tileWalk('d', 29.0)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.press(',')
time.sleep(0.6)
self.keyboard.press(',')
time.sleep(0.9)
self.keyboard.press('space')
