self.keyboard.tileWalk('w', 40.0)
self.keyboard.tileWalk('a', 18.0)
self.keyboard.tileWalk('w', 5.0)
self.keyboard.keyDown('d')
self.keyboard.tileWait(41.0)
self.keyboard.keyUp('d')
self.keyboard.keyDown('s')
self.keyboard.tileWait(16.5)
self.keyboard.keyUp('s')
