self.keyboard.tileWalk('w', 40.0)
self.keyboard.tileWalk('a', 18.0)
self.keyboard.tileWalk('w', 5.0)
self.keyboard.tileWalk('d', 30.5)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.42)
self.keyboard.press('space')
self.keyboard.keyUp('w')
time.sleep(1.4)
self.keyboard.multiTileWalk(['d', 'w'], 17.0)
self.keyboard.tileWalk('d', 2.0)
self.keyboard.press(',')
self.keyboard.press(',')
