self.keyboard.walk('a', 30.5)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.42)
self.keyboard.press('space')
self.keyboard.keyUp('s')
time.sleep(1.4)
self.keyboard.multiWalk(['a', 's'], 17.0)
self.keyboard.walk('Rightkey', 2.0)
self.keyboard.press(',')
self.keyboard.press(',')
