self.keyboard.tileWalk('w', 40.0)
self.keyboard.tileWalk('a', 18.0)
self.keyboard.tileWalk('w', 5.0)
self.keyboard.keyDown('d')
self.keyboard.tileWait(5.5)
self.keyboard.keyDown('s')
self.keyboard.tileWait(11.0)
self.keyboard.keyUp('d')
self.keyboard.tileWait(14.5)
self.keyboard.keyDown('d')
self.keyboard.keyUp('s')
self.keyboard.tileWait(8.5)
self.keyboard.keyUp('d')
self.keyboard.keyDown('s')
self.keyboard.tileWait(24.0)
self.keyboard.keyDown('d')
self.keyboard.tileWait(9.5)
self.keyboard.keyUp('s')
self.keyboard.tileWait(40.0)
self.keyboard.keyDown('s')
self.keyboard.tileWait(10.0)
self.keyboard.keyUp('s')
self.keyboard.keyUp('d')
