self.keyboard.tileWalk('w', 40.0)
self.keyboard.tileWalk('a', 18.0)
self.keyboard.tileWalk('w', 5.0)
self.keyboard.keyDown('d')
self.keyboard.tileWait(5.0)
self.keyboard.keyDown('s')
self.keyboard.tileWait(14.5)
self.keyboard.keyUp('d')
self.keyboard.tileWait(10.5)
self.keyboard.keyDown('d')
self.keyboard.keyUp('s')
self.keyboard.tileWait(8.0)
self.keyboard.keyUp('d')
self.keyboard.keyDown('s')
self.keyboard.tileWait(33.5)
self.keyboard.keyDown('d')
self.keyboard.tileWait(10.0)
self.keyboard.keyUp('d')
self.keyboard.tileWait(14.0)
self.keyboard.keyDown('d')
self.keyboard.tileWait(0.5)
self.keyboard.keyUp('s')
self.keyboard.tileWait(17.0)
self.keyboard.keyUp('d')
