self.keyboard.tileWalk('w', 40.0)
self.keyboard.tileWalk('a', 18.0)
self.keyboard.tileWalk('w', 5.0)
self.keyboard.tileWalk('d', 25.5)
time.sleep(0.1)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.2)
self.keyboard.keyUp('w')
time.sleep(0.5)
self.keyboard.tileWalk('w', 9.0)
self.keyboard.tileWalk('a', 63.0)
self.keyboard.tileWalk('w', 2.5)
