self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('d')
time.sleep(0.25)
time.sleep(0.07)
self.keyboard.walk('s', 5.5)
self.keyboard.multiWalk(['s', 'a'], 25.0)
self.keyboard.walk('a', 5.0)
