self.keyboard.walk('d', 25.5)
time.sleep(0.1)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.2)
self.keyboard.keyUp('w')
time.sleep(0.5)
self.keyboard.walk('w', 9.0)
self.keyboard.walk('a', 63.0)
self.keyboard.walk('w', 2.5)
