self.keyboard.tileWalk('w', 40.0)
self.keyboard.tileWalk('a', 18.0)
self.keyboard.tileWalk('w', 5.0)
self.keyboard.keyDown('d')
self.keyboard.tileWait(5.5)
self.keyboard.keyDown('s')
self.keyboard.tileWait(15.0)
self.keyboard.keyUp('d')
self.keyboard.tileWait(9.0)
self.keyboard.keyUp('s')
self.keyboard.keyDown('d')
self.keyboard.tileWait(6.0)
self.keyboard.keyUp('d')
self.keyboard.keyDown('s')
self.keyboard.tileWait(82.5)
self.keyboard.keyDown('d')
self.keyboard.tileWait(13.0)
self.keyboard.keyUp('s')
self.keyboard.tileWait(6.0)
self.keyboard.keyUp('d')
self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('d')
time.sleep(0.25)
self.keyboard.keyDown('s')
self.keyboard.tileWait(4.0)
self.keyboard.keyUp('s')
time.sleep(0.07)
self.keyboard.keyDown('a')
self.keyboard.tileWait(40.0)
self.keyboard.keyUp('a')
self.keyboard.tileWalk('s', 5.5)
self.keyboard.multiTileWalk(['s', 'a'], 25.0)
self.keyboard.tileWalk('a', 5.0)
