self.keyboard.walk('a', 25.5)
time.sleep(0.1)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.2)
self.keyboard.keyUp('s')
time.sleep(0.5)
self.keyboard.walk('s', 9.0)
self.keyboard.walk('d', 63.0)
self.keyboard.walk('s', 2.5)
