self.keyboard.walk('w', 11.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('w')
time.sleep(0.1)
self.keyboard.multiWalk(['d', 'w'], 19.0)
self.keyboard.walk('w', 3.5)
