self.keyboard.tileWalk('w', 40.0)
self.keyboard.tileWalk('a', 18.0)
self.keyboard.tileWalk('w', 5.0)
self.keyboard.keyDown('d')
self.keyboard.tileWait(6.5)
self.keyboard.keyDown('s')
self.keyboard.tileWait(13.0)
self.keyboard.keyUp('d')
self.keyboard.tileWait(9.0)
self.keyboard.keyUp('s')
self.keyboard.keyDown('d')
self.keyboard.tileWait(9.0)
self.keyboard.keyDown('s')
self.keyboard.keyUp('d')
self.keyboard.tileWait(73.5)
self.keyboard.keyDown('a')
self.keyboard.tileWait(8.5)
self.keyboard.keyUp('s')
self.keyboard.keyUp('a')
