self.keyboard.tileWalk('w', 40.0)
self.keyboard.tileWalk('a', 18.0)
self.keyboard.tileWalk('w', 5.0)
self.keyboard.keyDown('d')
self.keyboard.tileWait(5.0)
self.keyboard.keyDown('s')
self.keyboard.tileWait(13.0)
self.keyboard.keyUp('d')
self.keyboard.tileWait(11.0)
self.keyboard.keyUp('s')
self.keyboard.keyDown('d')
self.keyboard.tileWait(9.0)
self.keyboard.keyDown('s')
self.keyboard.keyUp('d')
self.keyboard.tileWait(27.0)
self.keyboard.keyDown('d')
self.keyboard.tileWait(9.5)
self.keyboard.keyUp('s')
self.keyboard.tileWait(24.0)
self.keyboard.keyDown('s')
self.keyboard.tileWait(13.0)
self.keyboard.keyUp('d')
self.keyboard.tileWait(42.0)
self.keyboard.keyDown('d')
self.keyboard.tileWait(2.0)
self.keyboard.keyUp('s')
self.keyboard.keyUp('d')
