self.keyboard.tileWalk('a', 38.0)
self.keyboard.tileWalk('w', 32.0)
self.keyboard.multiTileWalk(['d', 's'], 10.0)
time.sleep(0.075)
self.keyboard.tileWalk('d', 29.0)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.press(',')
time.sleep(1.0)
self.keyboard.press(',')
time.sleep(1.9)
self.keyboard.keyDown('w')
self.keyboard.tileWait(3.5)
self.keyboard.keyUp('w')
self.keyboard.keyDown('d')
self.keyboard.tileWait(22.0)
self.keyboard.keyUp('d')
time.sleep(0.07)
self.keyboard.tileWalk('w', 9.5)
self.keyboard.tileWalk('s', 7.0)
self.keyboard.tileWalk('w', 32.0)
