self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.press(',')
time.sleep(1.0)
self.keyboard.press(',')
time.sleep(1.9)
time.sleep(0.07)
self.keyboard.walk('w', 9.5)
self.keyboard.walk('s', 7.0)
self.keyboard.walk('w', 32.0)
self.keyboard.multiWalk(['d', 's'], 10.0)
time.sleep(0.075)
self.keyboard.walk('d', 29.0)
