self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.press(',')
time.sleep(1.0)
self.keyboard.press(',')
time.sleep(1.9)
self.keyboard.multiWalk(['Rightkey', 's'], 12.0)
time.sleep(0.1)
self.keyboard.walk('s', 8.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('s')
time.sleep(0.4)
self.keyboard.walk('s', 4.0)
self.keyboard.walk('d', 4.0)
self.keyboard.walk('s', 9.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('s')
time.sleep(0.4)
self.keyboard.walk('s', 4.0)
self.keyboard.multiWalk(['s', 'a'], 10.0)
self.keyboard.multiWalk(['a', 'w'], 10.0)
time.sleep(0.075)
self.keyboard.walk('a', 29.0)
