self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(4.0)
self.keyboard.walk('d', 25.0)
self.keyboard.multiWalk(['s', 'd'], 6.0)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.multiWalk(['a', 'w'], 10.0)
time.sleep(0.075)
self.keyboard.walk('a', 29.0)
