self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(0.89)
self.keyboard.press(',')
time.sleep(1.24)
self.keyboard.press('.')
time.sleep(0.67)
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.multiWalk(['d', 's'], 10.0)
time.sleep(0.075)
self.keyboard.walk('d', 29.0)
