time.sleep(0.1)
self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('d')
time.sleep(0.08)
self.keyboard.walk('s', 3.0)
self.keyboard.press('space')
time.sleep(2.05)
self.keyboard.press(',')
self.keyboard.press(',')
time.sleep(0.85)
self.keyboard.press('space')
self.keyboard.press('.')
self.keyboard.press('.')
time.sleep(1.6)
