self.keyboard.tileWalk('a', 38.0)
self.keyboard.tileWalk('w', 32.0)
self.keyboard.keyDown('s')
self.keyboard.keyDown('d')
self.keyboard.tileWait(43.5)
self.keyboard.keyUp('d')
self.keyboard.tileWait(22.4)
self.keyboard.keyUp('s')
self.keyboard.keyDown('d')
self.keyboard.tileWait(6.8)
self.keyboard.keyUp('d')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.press('space')
time.sleep(3.0)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.tileWalk('d', 1.5)
