self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.press('space')
self.keyboard.multiWalk(['d', 's'], 10.0)
time.sleep(0.075)
self.keyboard.walk('d', 29.0)
