self.keyboard.multiWalk(['a', 'w'], 9.0)
time.sleep(0.075)
self.keyboard.walk('a', 38.0)
time.sleep(1.0)
self.keyboard.multiWalk(['s', 'd'], 10.0)
self.keyboard.multiWalk(['w', 'a'], 14.0)
self.keyboard.walk('a', 3.0)
