self.keyboard.tileWalk('a', 38.0)
self.keyboard.tileWalk('w', 32.0)
self.keyboard.multiTileWalk(['d', 's'], 9.0)
time.sleep(0.075)
self.keyboard.tileWalk('d', 38.0)
time.sleep(1.0)
self.keyboard.multiTileWalk(['w', 'a'], 10.0)
self.keyboard.multiTileWalk(['s', 'd'], 14.0)
self.keyboard.tileWalk('d', 3.0)
