self.keyboard.tileWalk('a', 38.0)
self.keyboard.tileWalk('w', 32.0)
self.keyboard.multiTileWalk(['d', 's'], 10.0)
time.sleep(0.075)
self.keyboard.tileWalk('d', 29.0)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(4.0)
self.keyboard.tileWalk('s', 8.0)
self.keyboard.tileWalk('d', 17.0)
self.keyboard.press(',')
self.keyboard.press(',')
