self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('space')
time.sleep(4.0)
self.keyboard.walk('s', 8.0)
self.keyboard.walk('d', 17.0)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.multiWalk(['d', 's'], 10.0)
time.sleep(0.075)
self.keyboard.walk('d', 29.0)
