time.sleep(0.12)
self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.keyUp('a')
time.sleep(0.07)
self.keyboard.walk('s', 27.0)
time.sleep(0.1)
self.keyboard.walk('a', 42.0)
time.sleep(0.1)
self.keyboard.walk('w', 12.0)
