self.keyboard.walk('d', 14.0)
time.sleep(0.12)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.multiWalk(['w', 'd'], 21.0)
self.keyboard.walk('w', 6.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.walk('w', 4.0)
self.keyboard.walk('a', 4.0)
self.keyboard.walk('w', 9.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.walk('w', 4.0)
self.keyboard.multiWalk(['w', 'd'], 10.0)
self.keyboard.walk('w', 2.0)
