self.keyboard.walk('a', 14.0)
time.sleep(0.12)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('s')
time.sleep(0.4)
self.keyboard.multiWalk(['s', 'a'], 21.0)
self.keyboard.walk('s', 6.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('s')
time.sleep(0.4)
self.keyboard.walk('s', 4.0)
self.keyboard.walk('d', 4.0)
self.keyboard.walk('s', 9.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('s')
time.sleep(0.4)
self.keyboard.walk('s', 4.0)
self.keyboard.multiWalk(['s', 'a'], 10.0)
self.keyboard.walk('s', 2.0)
