self.keyboard.tileWalk('a', 20.0)
self.keyboard.tileWalk('d', 24.0)
self.keyboard.tileWalk('s', 11.0)
self.keyboard.multiTileWalk(['s', 'd'], 23.0)
self.keyboard.tileWalk('a', 1.0)
self.keyboard.tileWalk('w', 4.5)
self.keyboard.tileWalk('d', 3.0)
self.keyboard.multiTileWalk(['d', 'w'], 2.0)
self.keyboard.tileWalk('d', 17.0)
self.keyboard.press('space')
time.sleep(0.3)
self.keyboard.keyDown('d')
time.sleep(0.2)
self.keyboard.keyUp('d')
time.sleep(0.5)
self.keyboard.tileWalk('d', 6.0)
time.sleep(0.05)
self.keyboard.tileWalk('s', 2.5)
self.keyboard.keyDown('e')
time.sleep(0.1)
self.keyboard.keyUp('e')
self.keyboard.keyDown('a')
time.sleep(1.85)
self.keyboard.press('space')
self.keyboard.press('space')
time.sleep(2.75)
self.keyboard.keyUp('a')
self.keyboard.keyDown('s')
time.sleep(1.15)
self.keyboard.keyUp('s')
self.keyboard.press('space')
time.sleep(2.0)
