self.keyboard.tileWalk('a', 20.0)
self.keyboard.keyDown('w')
self.keyboard.tileWait(6.6)
self.keyboard.keyUp('w')
time.sleep(0.12)
self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.keyUp('a')
time.sleep(0.07)
self.keyboard.tileWalk('s', 27.0)
time.sleep(0.1)
self.keyboard.tileWalk('a', 38.0)
time.sleep(0.1)
self.keyboard.multiTileWalk(['a', 's'], 32.0)
self.keyboard.tileWalk('a', 2.0)
