time.sleep(0.12)
self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.keyUp('d')
time.sleep(0.07)
self.keyboard.walk('w', 27.0)
time.sleep(0.1)
self.keyboard.walk('d', 38.0)
time.sleep(0.1)
self.keyboard.multiWalk(['d', 'w'], 32.0)
self.keyboard.walk('d', 2.0)
