time.sleep(0.12)
self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.keyUp('a')
time.sleep(0.07)
self.keyboard.walk('s', 27.0)
time.sleep(0.1)
self.keyboard.walk('a', 50.0)
time.sleep(0.1)
self.keyboard.multiWalk(['a', 'w'], 18.0)
