self.keyboard.walk('d', 24.0)
self.keyboard.walk('s', 11.0)
self.keyboard.multiWalk(['s', 'd'], 5.0)
self.keyboard.walk('s', 10.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('s')
self.keyboard.multiWalk(['a', 's'], 19.0)
self.keyboard.walk('s', 3.5)
