self.keyboard.tileWalk('a', 20.0)
self.keyboard.tileWalk('d', 24.0)
self.keyboard.tileWalk('s', 11.0)
self.keyboard.multiTileWalk(['s', 'd'], 5.0)
self.keyboard.tileWalk('s', 10.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('s')
self.keyboard.multiTileWalk(['a', 's'], 19.0)
self.keyboard.tileWalk('s', 3.5)
