self.keyboard.walk('a', 24.0)
self.keyboard.walk('w', 11.0)
self.keyboard.multiWalk(['w', 'a'], 5.0)
self.keyboard.walk('w', 10.0)
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('w')
self.keyboard.multiWalk(['d', 'w'], 19.0)
self.keyboard.walk('w', 3.5)
