self.keyboard.tileWalk('a', 20.0)
self.keyboard.keyDown('w')
self.keyboard.tileWait(6.6)
self.keyboard.keyUp('w')
time.sleep(0.12)
self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('a')
self.keyboard.tileWalk('w', 5.0)
self.keyboard.multiTileWalk(['w', 'a'], 23.0)
self.keyboard.tileWalk('a', 2.0)
