time.sleep(0.12)
self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('d')
self.keyboard.walk('w', 3.0)
self.keyboard.multiWalk(['w', 'd'], 15.0)
self.keyboard.walk('d', 8.0)
