hive_slot = int(self.setdat.get("hive_number", self.setdat.get("hiveslot", 3)) or 3)
self.keyboard.walk('w', 5.0)
self.keyboard.walk('d', 9.2 * hive_slot - 4)
self.keyboard.multiWalk(['s', 'a'], 67.5)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.walk('w', 23.5)
self.keyboard.multiWalk(['w', 'd'], 31.5)
self.keyboard.walk('d', 10.0)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.walk('w', 20.0)
self.keyboard.multiWalk(['w', 'a'], 5.0)
self.keyboard.walk('a', 7.0)
self.keyboard.walk('w', 1.0)
self.keyboard.walk('d', 8.0)
self.keyboard.walk('s', 14.0)
