hive_slot = int(self.setdat.get("hive_number", self.setdat.get("hiveslot", 3)) or 3)
self.keyboard.walk('w', 5.0)
self.keyboard.walk('d', 9.2 * hive_slot - 4)
self.keyboard.multiWalk(['s', 'a'], 88.875)
self.keyboard.walk('a', 27.0)
time.sleep(0.05)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.walk('w', 17.0)
self.keyboard.walk('a', 17.0)
self.keyboard.walk('w', 18.0)
self.keyboard.walk('s', 10.0)
self.keyboard.multiWalk(['s', 'd'], 7.0)
