hive_slot = int(self.setdat.get("hive_number", self.setdat.get("hiveslot", 3)) or 3)
self.keyboard.walk('w', 5.0)
self.keyboard.walk('d', 9.2 * hive_slot - 4)
self.keyboard.multiWalk(['s', 'a'], 67.5)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.walk('w', 31.0)
self.keyboard.walk('a', 7.8)
self.keyboard.walk('s', 10.0)
self.keyboard.walk('d', 5.0)
self.keyboard.walk('w', 1.5)
self.keyboard.walk('a', 60.0)
self.keyboard.walk('w', 49.5)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.walk('w', 35.5)
self.keyboard.walk('d', 3.0)
self.keyboard.walk('s', 7.0)
self.keyboard.press('.')
self.keyboard.press('.')
