hive_slot = int(self.setdat.get("hive_number", self.setdat.get("hiveslot", 3)) or 3)
self.keyboard.walk('w', 5.0)
self.keyboard.walk('d', 9.2 * hive_slot - 4)
self.keyboard.multiWalk(['s', 'a'], 44.75)
self.keyboard.walk('a', 52.5)
self.keyboard.multiWalk(['s', 'd'], 2.8)
self.keyboard.walk('s', 7.7)
self.keyboard.walk('a', 20.5)
self.keyboard.walk('w', 6.5)
self.keyboard.multiWalk(['w', 'a'], 20.0)
self.keyboard.walk('w', 3.0)
self.keyboard.walk('a', 3.0)
self.keyboard.walk('d', 5.0)
self.keyboard.multiWalk(['d', 'w'], 10.0)
self.keyboard.walk('s', 3.0)
