hive_slot = int(self.setdat.get("hive_number", self.setdat.get("hiveslot", 3)) or 3)
self.keyboard.walk('w', 5.0)
self.keyboard.walk('d', 9.2 * hive_slot - 4)
self.keyboard.keyDown('space')
self.keyboard.keyDown('d')
time.sleep(0.1)
self.keyboard.keyUp('space')
self.keyboard.walk('w', 2.0)
self.keyboard.walk('w', 1.8)
self.keyboard.walk('w', 30.0)
self.keyboard.keyUp('d')
self.keyboard.keyDown('space')
time.sleep(0.3)
self.keyboard.keyUp('space')
self.keyboard.walk('d', 4.0)
self.keyboard.walk('w', 5.0)
self.keyboard.walk('d', 3.0)
self.keyboard.keyDown('space')
time.sleep(0.3)
self.keyboard.keyUp('space')
self.keyboard.walk('w', 5.0)
self.keyboard.multiWalk(['a', 'w'], 2.0)
self.keyboard.walk('w', 8.0)
self.keyboard.keyDown('d')
self.keyboard.walk('w', 11.0)
self.keyboard.keyDown('space')
self.keyboard.keyUp('d')
time.sleep(0.2)
self.keyboard.keyUp('space')
time.sleep(1.1)
self.keyboard.keyDown('space')
time.sleep(0.2)
self.keyboard.keyUp('space')
self.keyboard.walk('w', 18.0)
self.keyboard.walk('a', 7.0)
