hive_slot = int(self.setdat.get("hive_number", self.setdat.get("hiveslot", 3)) or 3)
self.keyboard.walk('w', 5.0)
self.keyboard.walk('d', 9.2 * hive_slot - 4)
self.keyboard.press('.')
self.keyboard.walk('s', 39.0)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.walk('w', 51.0)
self.keyboard.walk('s', 15.0)
