hive_slot = int(self.setdat.get("hive_number", self.setdat.get("hiveslot", 3)) or 3)
self.keyboard.walk('w', 5.0)
self.keyboard.walk('d', 9.2 * hive_slot - 4)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('.')
time.sleep(0.2)
self.keyboard.multiWalk(['w', 'd'], 55.75)
self.keyboard.walk('w', 26.5)
self.keyboard.multiWalk(['w', 'd'], 10.0)
self.keyboard.walk('a', 5.0)
