hive_slot = int(self.setdat.get("hive_number", self.setdat.get("hiveslot", 3)) or 3)
self.keyboard.walk('w', 5.0)
self.keyboard.walk('d', 9.2 * hive_slot - 4)
self.keyboard.keyDown('e')
time.sleep(0.1)
self.keyboard.keyUp('e')
time.sleep(0.5)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.keyDown('d')
time.sleep(1.0)
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.press('space')
time.sleep(2.9)
self.keyboard.keyUp('d')
self.keyboard.keyDown('w')
self.keyboard.keyDown('a')
time.sleep(1.6)
self.keyboard.press('space')
time.sleep(1.0)
self.keyboard.multiWalk(['w', 'a'], 14.0)
self.keyboard.walk('w', 10.0)
self.keyboard.multiWalk(['s', 'd'], 7.0)
