hive_slot = int(self.setdat.get("hive_number", self.setdat.get("hiveslot", 3)) or 3)
self.keyboard.walk('w', 5.0)
self.keyboard.walk('d', 9.2 * hive_slot - 4)
self.keyboard.multiWalk(['s', 'a'], 67.5)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.walk('w', 31.0)
self.keyboard.walk('a', 7.8)
self.keyboard.walk('s', 10.0)
self.keyboard.walk('d', 5.0)
self.keyboard.walk('w', 1.5)
self.keyboard.walk('a', 60.0)
self.keyboard.walk('d', 3.75)
self.keyboard.walk('w', 38.0)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.walk('d', 14.0)
self.keyboard.multiWalk(['w', 'a'], 15.0)
self.keyboard.walk('s', 1.0)
time.sleep(0.2)
self.keyboard.walk('d', 16.0)
self.keyboard.walk('w', 49.0)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.walk('d', 10.0)
self.keyboard.multiWalk(['d', 'w'], 12.0)
self.keyboard.multiWalk(['s', 'a'], 7.0)
self.keyboard.press(',')
self.keyboard.press(',')
