hive_slot = int(self.setdat.get("hive_number", self.setdat.get("hiveslot", 3)) or 3)
self.keyboard.walk('w', 5.0)
self.keyboard.walk('d', 9.2 * hive_slot - 4)
self.keyboard.multiWalk(['s', 'a'], 67.5)
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.press('.')
self.keyboard.walk('w', 31.0)
self.keyboard.multiWalk(['w', 'a'], 7.0)
self.keyboard.walk('a', 30.25)
self.keyboard.multiWalk(['w', 'a'], 30.0)
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.multiWalk(['s', 'a'], 10.0)
