hive_slot = int(self.setdat.get("hive_number", self.setdat.get("hiveslot", 3)) or 3)
self.keyboard.walk('w', 5.0)
self.keyboard.walk('d', 9.2 * hive_slot - 4)
self.keyboard.keyDown('e')
time.sleep(0.1)
self.keyboard.keyUp('e')
self.keyboard.keyDown('a')
time.sleep(1.8)
self.keyboard.press('space')
self.keyboard.press('space')
time.sleep(2.75)
self.keyboard.keyUp('a')
self.keyboard.press(',')
self.keyboard.press(',')
self.keyboard.keyDown('w')
self.keyboard.keyDown('a')
time.sleep(0.9)
self.keyboard.keyUp('a')
time.sleep(1.5)
self.keyboard.keyUp('w')
self.keyboard.press('space')
time.sleep(1.0)
