hive_slot = int(self.setdat.get("hive_number", self.setdat.get("hiveslot", 3)) or 3)
self.keyboard.walk('w', 5.0)
self.keyboard.walk('d', 9.2 * hive_slot - 4)
self.keyboard.walk('s', 14.0)
self.keyboard.press('.')
self.keyboard.walk('d', 25.0)
self.keyboard.walk('w', 15.0)
self.keyboard.walk('s', 9.0)
self.keyboard.press('.')
