self.keyboard.walk('s', 12.0)
time.sleep(0.1)
self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('a')
time.sleep(0.4)
self.keyboard.walk('a', 1.0)
self.keyboard.walk('s', 4.0)
time.sleep(0.1)
self.keyboard.walk('a', 10.0)
self.keyboard.multiWalk(['a', 's'], 18.0)
self.keyboard.walk('s', 2.5)
self.keyboard.walk('d', 5.0)
