self.keyboard.tileWalk('d', 5.0)
self.keyboard.keyDown('d')
self.keyboard.tileWait(25.5)
self.keyboard.keyDown('s')
self.keyboard.tileWait(13.0)
self.keyboard.keyUp('d')
self.keyboard.tileWait(4.0)
self.keyboard.keyUp('s')
