self.keyboard.tileWalk('d', 5.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.6)
self.keyboard.keyUp('s')
time.sleep(0.3)
self.keyboard.tileWalk('s', 21.0)
self.keyboard.multiTileWalk(['d', 's'], 8.0)
