self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('d')
time.sleep(0.25)
time.sleep(0.07)
self.keyboard.walk('s', 5.5)
self.keyboard.multiWalk(['s', 'a'], 25.0)
self.keyboard.walk('a', 5.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.6)
self.keyboard.keyUp('s')
time.sleep(0.3)
self.keyboard.multiWalk(['s', 'a'], 4.0)
self.keyboard.walk('a', 9.0)
self.keyboard.multiWalk(['s', 'a'], 7.5)
self.keyboard.walk('s', 42.0)
self.keyboard.multiWalk(['s', 'd'], 15.0)
