self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.walk('w', 4.0)
self.keyboard.walk('a', 8.0)
self.keyboard.walk('w', 9.0)
self.keyboard.walk('s', 6.0)
time.sleep(0.1)
self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('a')
time.sleep(0.8)
time.sleep(0.1)
time.sleep(3.0)
self.keyboard.multiWalk(['d', 'w'], 2.0)
self.keyboard.walk('w', 20.0)
self.keyboard.walk('a', 22.0)
self.keyboard.walk('d', 5.0)
