self.keyboard.tileWalk('d', 5.0)
self.keyboard.keyDown('d')
self.keyboard.tileWait(16.5)
self.keyboard.keyDown('w')
self.keyboard.tileWait(9.5)
self.keyboard.keyUp('d')
self.keyboard.tileWait(7.5)
self.keyboard.keyUp('w')
self.keyboard.keyDown('w')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('w')
time.sleep(0.4)
self.keyboard.tileWalk('w', 4.0)
self.keyboard.tileWalk('a', 8.0)
self.keyboard.tileWalk('w', 9.0)
self.keyboard.tileWalk('s', 6.0)
time.sleep(0.1)
self.keyboard.keyDown('a')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('a')
time.sleep(0.8)
self.keyboard.keyDown('e')
time.sleep(0.1)
self.keyboard.keyUp('e')
time.sleep(3.0)
self.keyboard.multiTileWalk(['d', 'w'], 2.0)
self.keyboard.tileWalk('w', 20.0)
self.keyboard.tileWalk('a', 22.0)
