self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.45)
self.keyboard.keyUp('s')
time.sleep(0.4)
self.keyboard.walk('s', 4.0)
self.keyboard.walk('d', 8.0)
self.keyboard.walk('s', 9.0)
self.keyboard.walk('w', 6.0)
time.sleep(0.1)
self.keyboard.keyDown('d')
self.keyboard.press('space')
time.sleep(0.4)
self.keyboard.keyUp('d')
time.sleep(0.8)
time.sleep(0.1)
time.sleep(3.0)
self.keyboard.multiWalk(['a', 's'], 2.0)
self.keyboard.walk('s', 20.0)
self.keyboard.walk('d', 22.0)
self.keyboard.walk('a', 5.0)
