self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.6)
self.keyboard.keyUp('s')
time.sleep(0.3)
self.keyboard.multiWalk(['s', 'd'], 4.0)
self.keyboard.walk('s', 10.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.5)
self.keyboard.keyUp('s')
time.sleep(0.4)
self.keyboard.walk('s', 2.0)
self.keyboard.multiWalk(['s', 'a'], 15.0)
self.keyboard.walk('s', 5.0)
self.keyboard.walk('d', 5.0)
