self.keyboard.tileWalk('d', 5.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.6)
self.keyboard.keyUp('s')
time.sleep(0.3)
self.keyboard.multiTileWalk(['s', 'a'], 4.0)
self.keyboard.tileWalk('a', 9.0)
self.keyboard.multiTileWalk(['s', 'a'], 16.0)
self.keyboard.tileWalk('a', 2.0)
