self.keyboard.tileWalk('d', 5.0)
self.keyboard.keyDown('s')
self.keyboard.press('space')
time.sleep(0.6)
self.keyboard.keyUp('s')
time.sleep(0.3)
self.keyboard.keyDown('d')
self.keyboard.keyDown('s')
self.keyboard.tileWait(28.5)
self.keyboard.keyUp('d')
self.keyboard.tileWait(35.0)
self.keyboard.keyUp('s')
self.keyboard.keyDown('d')
self.keyboard.tileWait(1.0)
self.keyboard.keyUp('d')
